name: Build & Release (Windows)

on:
  push:
    branches: [ add/pyinstaller-workflow ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller
        shell: bash
        run: |
          if [ -f "DIM-Creator.spec" ]; then
            pyinstaller -y DIM-Creator.spec
          else
            pyinstaller app.py \
              --noconfirm --onefile --noconsole \
              --name DIM-Creator \
              --add-data "assets;assets" \
              --icon "assets/images/logo/x128.ico" \
              --hidden-import qfluentwidgets
          fi

      - name: List outputs (before packaging)
        shell: pwsh
        run: |
          if (Test-Path dist) {
            Get-ChildItem -Recurse -File dist | Select-Object FullName, Length | Format-Table -AutoSize
          } else {
            Write-Host "dist folder not found."
          }

      - name: Ensure canonical docs in dist
        shell: pwsh
        run: |
          $readme = @("README.md","README.MD","README.txt","README","ReadMe.md") |
            Where-Object { Test-Path $_ } | Select-Object -First 1
          if ($readme) { Copy-Item $readme "dist/README.md" -Force }

          $license = @("LICENSE","LICENSE.md","LICENSE.txt","LICENCE","LICENCE.md","LICENCE.txt") |
            Where-Object { Test-Path $_ } | Select-Object -First 1
          if ($license) { Copy-Item $license "dist/LICENSE" -Force }

      - name: Package ZIP with version + docs (sanitize name)
        shell: pwsh
        run: |
          $verRaw = $env:GITHUB_REF_NAME
          if (-not $verRaw) { $verRaw = "dev" }
          $ver = ($verRaw -replace '[^0-9A-Za-z._-]', '_')

          if (!(Test-Path "dist/DIM-Creator.exe")) {
            Get-ChildItem -Recurse -File dist | Select-Object FullName, Length | Format-Table -AutoSize
            throw "Executable not found at dist/DIM-Creator.exe"
          }

          $items = @("dist/DIM-Creator.exe")
          if (Test-Path "dist/README.md") { $items += "dist/README.md" }
          if (Test-Path "dist/LICENSE")   { $items += "dist/LICENSE"   }

          $zipPath = "dist/DIM-Creator_${ver}_win-x64.zip"
          if (Test-Path $zipPath) { Remove-Item $zipPath -Force }

          Compress-Archive -Path $items -DestinationPath $zipPath -Force

      - name: Upload artifact (CI)
        uses: actions/upload-artifact@v4
        with:
          name: dim-creator-windows
          path: |
            dist/DIM-Creator.exe
            dist/*.zip
          if-no-files-found: error

      - name: Attach to Release (on tags)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/DIM-Creator.exe
            dist/*.zip
          generate_release_notes: true
